language: java

sudo: false

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EiQTFg+2gLBHZNXZ8kECrOQj8KaXM+/L1yydRpefFhc0Nu44eq5ZDyN1AsgvhrINfw5Fm6opE8YjGkB6h6cDVFDUg1gPahL4QC7ovR1nbxDlbsljY4S+i26SZLjCzw0Jh7PUt/IcXaOVwSghQOD/9kWm/77Zi1FMpQJMft5CKQ4="

addons:
  coverity_scan:
    project:
      name: "senbox-org/s3tbx"
      description: "Build submitted via Travis CI"
    notification_email: stb-coverity@thor.si.c-s.fr
    build_command_prepend: ""
    build_command: "mvn -DskipTests=true clean compile"
    branch_pattern: coverity_scan

before_install:
  # Work around discontinued nexus.codehaus.org (see https://github.com/travis-ci/travis-ci/issues/4629)
  # For building, everything is available in nexus.senbox.net, which is stored in pom.xml,
  # so we just completely remove the default repositories settings
  - sed -i -n '/<repositories>/{p; :a; N; /<\/repositories>/!ba; s/.*\n//}; p' ~/.m2/settings.xml

install:
  - true

script:
  - mvn clean install -B -V
