language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
  # Work around discontinued nexus.codehaus.org (see https://github.com/travis-ci/travis-ci/issues/4629)
  # For building, everything is available in nexus.senbox.net, which is stored in pom.xml,
  # so we just completely remove the default repositories settings
  - sed -i -n '/<repositories>/{p; :a; N; /<\/repositories>/!ba; s/.*\n//}; p' ~/.m2/settings.xml

before_script:
  # Avoid "java.lang.IllegalStateException: endPosTable already set"
  # by cleaning up the target dirs before building
  - mvn clean

